/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'jobType' : IDL.Text,
  'description' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'posted' : IDL.Int,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'company' : IDL.Text,
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'initializeSampleData' : IDL.Func([], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'jobType' : IDL.Text,
    'description' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'posted' : IDL.Int,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'company' : IDL.Text,
  });
  
  return IDL.Service({
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'initializeSampleData' : IDL.Func([], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };