/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Job {
  'id' : bigint,
  'title' : string,
  'jobType' : string,
  'description' : string,
  'skills' : Array<string>,
  'location' : string,
  'posted' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'quote' : string,
  'author' : string,
  'company' : string,
}
export interface _SERVICE {
  'addJob' : ActorMethod<
    [string, string, string, string, Array<string>],
    bigint
  >,
  'addTestimonial' : ActorMethod<[string, string, string], bigint>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'submitApplication' : ActorMethod<
    [string, string, string, Array<string>, string],
    bigint
  >,
  'submitContactMessage' : ActorMethod<[string, string, string], bigint>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];